// Code generated by mockery v2.28.1. DO NOT EDIT.

package mocks

import (
	context "context"

	kafka "github.com/segmentio/kafka-go"

	mock "github.com/stretchr/testify/mock"
)

// WriterInterface is an autogenerated mock type for the WriterInterface type
type WriterInterface struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *WriterInterface) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteMessages provides a mock function with given fields: ctx, msgs
func (_m *WriterInterface) WriteMessages(ctx context.Context, msgs ...kafka.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewWriterInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewWriterInterface creates a new instance of WriterInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWriterInterface(t mockConstructorTestingTNewWriterInterface) *WriterInterface {
	mock := &WriterInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
